version: "2"

services: 
  backend:
    build: .  
    ports:
      - "8080:8080"
  front:
    image: trion/ng-cli:12.2.10
    command: >
      sh -c "
        npm install;
        ng serve --host 0.0.0.0;"
    ports:
      - "4200:4200"
    volumes:
      - ./challenge-front:/app
    working_dir: /app
    











